[package]
name = "beet_router"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description = "File based router for websites"
documentation.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[features]
parser = ["dep:beet_router_parser"]
bevy = [
	"dep:bevy",
	"dep:tokio",
	"dep:flume",
	"beet_rsx/bevy",
	"beet_rsx/bevy_default", #why
]
# for internal testing
_test_site = []

[dependencies]
beet_rsx = { workspace = true, features = ["serde"] }
bevy = { workspace = true, optional = true }
anyhow.workspace = true
ron.workspace = true
http.workspace = true
futures.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
beet_router_parser = { workspace = true, optional = true }
sweet = { workspace = true, features = ["fs"] }
tokio = { workspace = true, optional = true }
flume = { workspace = true, optional = true }

[dev-dependencies]
sweet = { workspace = true, features = ["test"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
beet_router = { path = "", features = ["parser", "bevy", "_test_site"] }
ron.workspace = true
tokio.workspace = true
