[package]
name = "beet_mcp"
edition = "2024"
publish = false
default-run = "beet_mcp"

[[bin]]
name = "beet_mcp"
path = "src/main.rs"


[dependencies]
#💡 utils
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std"] }
sweet = { path = "../../ws_sweet/sweet", features = ["fs"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"
dotenv = "0.15"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }

#💡 mcp
# fix: generic tool_box
rmcp = { path = "../../../rmcp/crates/rmcp", features = [
	"client",
	"__reqwest",
	"transport-io",
	"transport-sse-client",
	"transport-child-process",
] }
# rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", branch = "main", features = [
# 	"transport-io",
# ] }
axum = { version = "0.8", features = ["macros"] }
serde_json = "1"

#💡 rig
rig-core = { version = "0.12", features = ["derive"] }
#💡 sqlite
rig-sqlite = { version = "0.1", features = [] }
rusqlite = { version = "0.32", features = ["bundled"] }
sqlite-vec = "0.1"
tokio-rusqlite = { version = "0.6", features = [
	"bundled",
], default-features = false }
rustdoc-md = "0.1"
text-splitter = { version = "0.26", features = ["code", "markdown"] }
tree-sitter-rust = "0.24"
futures = "0.3"
rayon = "1"

[dev-dependencies]
tokio-test = "0.4"
sweet = { path = "../../ws_sweet/sweet", features = ["fs", "test"] }
