[package]
name = "beet_rsx"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description = "Cross domain authoring tools"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true


[features]
default = ["macros", "fs"]
fs = ["sweet/fs"]
bevy = ["dep:bevy", "serde", "dep:flume"]
# this is a hefty feature, pulls in bevy_render
bevy_default = ["bevy", "bevy/default"]
css = ["dep:lightningcss", "dep:parcel_selectors"]
macros = ["dep:beet_rsx_macros"]
parser = ["dep:quote", "dep:proc-macro2", "dep:beet_rsx_parser"]
serde = ["dep:serde", "dep:ron"]

[dependencies]
beet_rsx_parser = { workspace = true, optional = true }
beet_rsx_macros = { workspace = true, optional = true }
sweet.workspace = true

#💡 utils
thiserror.workspace = true
anyhow.workspace = true
extend.workspace = true
strum.workspace = true
rapidhash.workspace = true
strum_macros.workspace = true
prettyplease.workspace = true
once_cell.workspace = true
http.workspace = true

#💡 serde
serde = { workspace = true, optional = true }
ron = { workspace = true, optional = true }
quote = { workspace = true, optional = true }
proc-macro2 = { workspace = true, optional = true }

#💡 style
parcel_selectors = { version = "0.28", optional = true }
lightningcss = { version = "1.0.0-alpha.63", optional = true }

#💡 bevy
bevy = { workspace = true, optional = true }
flume = { workspace = true, optional = true }

#💡 native
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sweet = { workspace = true, features = ["fs"] }
tokio.workspace = true

#💡 wasm
[target.'cfg(target_arch = "wasm32")'.dependencies]
sweet = { workspace = true, features = ["web"] }
console_error_panic_hook.workspace = true
console_log.workspace = true
js-sys.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true


[dev-dependencies]
beet_rsx = { path = "", features = ["parser", "bevy"] }
sweet = { workspace = true, features = ["test"] }
