[package]
name = "beet_site"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

# use 'server' feature to build a server
# no-default-features to build a static site
[features]
# default = ["server"]
axum = []
lambda = []

[[bin]]
name = "beet_site"
path = "src/main.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow.workspace = true
beet = { workspace = true, features = ["server", "router"] }

tokio.workspace = true

# [dev-dependencies]
# beet = { workspace = true, default-features = false, features = ["router"] }
