[package]
name = "beet_site"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

# [features]
# setup = []

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow.workspace = true
beet = { workspace = true, features = ["router", "server"] }

tokio.workspace = true

# [dev-dependencies]
# beet = { workspace = true, default-features = false, features = ["router"] }
