[package]
name = "beet_site"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[features]
setup = ["beet/setup"]

[dependencies]
anyhow.workspace = true
serde.workspace = true

beet = { workspace = true, features = ["router"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
beet = { workspace = true, features = ["parser", "server"] }
tokio.workspace = true
