[package]
name = "beet_site"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true

sweet = { workspace = true, features = ["web"] }
beet = { workspace = true, features = ["web-server"] }

[build-dependencies]
anyhow.workspace = true
beet = { workspace = true, features = ["web-server", "build"] }
sweet = { workspace = true, features = ["fs"] }
