[package]
name = "beet_design"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = true

[features]
setup = []

[dependencies]
sweet.workspace = true
beet_rsx.workspace = true
beet_router.workspace = true

[dev-dependencies]
sweet = { workspace = true, features = ["test"] }
