# Copied from https://github.com/mrchantey/bevyhub/blob/main/.github/workflows/test.yml
name: 🔎 Test Crates
on:
  merge_group:
  pull_request:
  push:
    # branches:
    #   - main
    #   - release-*
env:
  CARGO_TERM_COLOR: always
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: 📂 Checkout
      uses: actions/checkout@v4
    - name: 📂 Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-v0
    # - name: 🔨 Install Bevy Dependencies
    #   if: runner.os == 'Linux'
    #   run: sudo apt-get update; sudo apt-get install --no-install-recommends g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 mold
    - name: 🔨📋 Install Just
      uses: extractions/setup-just@v1
    - name: 🔨 Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x  
    - name: 🔨 Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        default: true
        components: rustfmt
    - name: 🔨 Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: 🔨 Install cargo binstall
      uses: cargo-bins/cargo-binstall@main
      # run: cargo install cargo-binstall || true
    - name: 🔨 Install wasm bindgen cli
      run: cargo binstall wasm-bindgen-cli --version 0.2.100    || true
    - name: 🔨 Install sweet cli
      run: cargo binstall sweet-cli --version 0.3.0-rc.3        || true
    - name: 🔨 Install leptosfmt
      run: cargo binstall leptosfmt                             || true
    - name: 🔨📋 Init repo
      run: just init-repo
    - name: 🔎 Test
      run: just test-ci