[package]
name = "beet_rsx_parser"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true


[features]
default = ["html"]
fs = ["sweet/fs"]
css = ["dep:lightningcss"]
html = ["dep:scraper", "dep:ego-tree"]

[dependencies]
sweet.workspace = true
ron.workspace = true
anyhow.workspace = true
itertools.workspace = true

syn = { workspace = true, features = ["visit"] }
quote.workspace = true
heck.workspace = true
proc-macro2.workspace = true
rapidhash.workspace = true
rstml = { version = "0.12", features = ["rawtext-stable-hack"] }
scraper = { version = "0.23", optional = true }
ego-tree = { version = "0", optional = true }
# html5ever = { version = "0.30", optional = true }
proc-macro2-diagnostics = "0.10"
lightningcss = { workspace = true, optional = true }

[dev-dependencies]
sweet = { workspace = true, features = ["test"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
sweet = { workspace = true, features = ["fs"] }
